version: "3"

services:
    codeigniter:
        image: atsanna/codeigniter4:latest
        container_name: 'codeigniter'
        ports:
          - 8080:80
        links:
          - database
        volumes:
          - ./www:/var/www/html
             
    database:
        image: mariadb:10.5.5
        container_name: 'database'
        ports:
          - 3307:3306
        volumes:
          - ./www/database/mysql:/var/lib/mysql
          - ./www/database/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123
          # MYSQL_DATABASE: pw
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'phpmyadmin'
        links:
          - database
        environment:
          PMA_HOST: database
          PMA_PORT: 3306
        ports:
          - 8081:80
        volumes:
          - ./www/database/sessions:/sessions
